sudo: required
services:
  - docker


before_install:
  - docker build -t niteshldd/docker-public -f Dockerfile.dev .



script:
  - docker run niteshldd/docker-public npm test


deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker_pub"
  env: "DockerPub-env"
  bucket_name: "elasticbeanstalk-us-west-2-409888909294"
  bucket_path: "docker_pub"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"