version: '3'
services:
  web:
    build:
      context: .   #to copy the file 
      dockerfile: Dockerfile.dev # docker file 

    ports:
      - "4600:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]